## Merge and Clean Trip History Data

#### Import Dependencies

In [31]:
import pandas as pd
import os
from glob import glob

#### Read Data File

In [37]:
#Assigned a variable for all the csv files 
DataBikeTripFiles = ["RawData/CityBikeTripData/JC-201801-citibike-tripdata.csv.zip", "RawData/CityBikeTripData/JC-201802-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201803-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201804-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201805-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201806-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201807-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201808-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201809-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201810-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201811-citibike-tripdata.csv.zip","RawData/CityBikeTripData/JC-201812-citibike-tripdata.csv.zip"]

#### Iterate through files to create a single dataframe with data for each month

In [42]:
dataframe = []
for d in DataBikeTripFiles:
    dataframe.append(pd.read_csv(d))
BikeTripDataframe = pd.concat(dataframe, ignore_index=True)

In [44]:
BikeTripDataframe.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1

#### Replace 1 and 2 for Male and Female Value in the Gender Column

In [58]:
BikeTripDataframe["gender"].replace([1, 2], ["Male","Female"], inplace=True)

In [59]:
BikeTripDataframe.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,Male
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,Female
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,Male
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,Male
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,Male

#### Add Current Year Column to DataFrame

In [61]:
BikeTripDataframe.insert(14, "current year", 2018, True)

In [62]:
BikeTripDataframe

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,current year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,2018,Male
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2018,Female
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,2018,Male
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,2018,Male
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,2018,Male
5,613,2018-01-01 22:05:05.8740,2018-01-01 22:15:19.4190,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,31859,Subscriber,1982,2018,Male
6,290,2018-01-02 12:13:51.7940,2018-01-02 12:18:42.1070,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31694,Subscriber,1958,2018,Male
7,381,2018-01-02 12:50:03.3430,2018-01-02 12:56:24.6440,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,31754,Subscriber,1989,2018,Female
8,318,2018-01-02 13:55:58.2430,2018-01-02 14:01:16.8810,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,31816,Subscriber,1960,2018,Male
9,1852,2018-01-02 16:55:29.6390,2018-01-02 17:26:22.3050,3183,Exchange Place,40.716247,-74.033459,3281,Leonard Gordon Park,40.745910,-74.057271,31754,Subscriber,1976,2018,Male
10,460,2018-01-02 17:01:50.5860,2018-01-02 17:09:31.4340,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33463,Subscriber,1989,2018,Female
11,403,2018-01-02 17:05:12.2360,2018-01-02 17:11:55.2630,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,26256,Subscriber,1985,2018,Male
12,264,2018-01-02 17:05:12.6730,2018-01-02 17:09:37.4020,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29616,Subscriber,1974,2018,Male
13,282,2018-01-02 17:19:56.6090,2018-01-02 17:24:39.5340,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29681,Subscriber,1976,2018,Male
14,308,2018-01-02 17:31:45.9880,2018-01-02 17:36:54.3590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31949,Subscriber,1968,2018,Male
15,561,2018-01-02 17:32:54.8400,2018-01-02 17:42:16.3140,3183,Exchange Place,40.716247,-74.033459,3269,Brunswick & 6th,40.726012,-74.050389,29591,Subscriber,1976,2018,Male
16,114,2018-01-02 17:37:44.3450,2018-01-02 17:39:38.8760,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31925,Subscriber,1988,2018,Male
17,302,2018-01-02 17:54:04.8770,2018-01-02 17:59:06.9730,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31777,Subscriber,1990,2018,Male
18,230,2018-01-02 17:58:24.6360,2018-01-02 18:02:15.6320,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31763,Subscriber,1992,2018,Male
19,596,2018-01-02 18:05:59.6240,2018-01-02 18:15:55.8590,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29662,Subscriber,1992,2018,Male
20,826,2018-01-02 18:10:58.8600,2018-01-02 18:24:45.1600,3183,Exchange Place,40.716247,-74.033459,3194,McGinley Square,40.725340,-74.067622,31765,Subscriber,1989,2018,Male
21,368,2018-01-02 18:13:41.8510,2018-01-02 18:19:49.9780,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31695,Subscriber,1985,2018,Male
22,291,2018-01-02 18:18:41.6860,2018-01-02 18:23:33.0620,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31934,Subscriber,1980,2018,Male
23,250,2018-01-02 18:20:06.1050,2018-01-02 18:24:16.1640,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31880,Subscriber,1995,2018,Male
24,199,2018-01-02 18:31:11.9870,2018-01-02 18:34:31.1880,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29623,Subscriber,1980,2018,Male
25,225,2018-01-02 18:38:50.5100,2018-01-02 18:42:36.2120,3183,Exchange Place,40.716247,-74.033459,3185,City Hall,40.717733,-74.043845,31691,Subscriber,1992,2018,Male
26,242,2018-01-02 18:41:29.5240,2018-01-02 18:45:32.3240,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26314,Subscriber,1981,2018,0
27,214,2018-01-02 18:42:30.3030,2018-01-02 18:46:04.4630,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29581,Subscriber,1991,2018,Male
28,218,2018-01-02 19:29:20.7870,2018-01-02 19:32:59.1490,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31954,Subscriber,1991,2018,Male
29,318,2018-01-02 19:30:19.4880,2018-01-02 19:35:37.5450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29615,Subscriber,1978,2018,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353862,747,2018-12-10 20:33:10.0440,2018-12-10 20:45:37.2790,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29519,Subscriber,1958,2018,Male
353863,1124,2018-12-11 06:19:14.0610,2018-12-11 06:37:58.7960,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29657,Subscriber,1977,2018,Male
353864,648,2018-12-11 12:01:04.1040,2018-12-11 12:11:52.9080,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26287,Subscriber,1994,2018,Male
353865,575,2018-12-11 17:46:56.6360,2018-12-11 17:56:31.6520,3694,Jackson Square,40.711130,-74.078900,3191,Union St,40.718211,-74.083639,29239,Subscriber,1958,2018,Male
353866,961,2018-12-12 06:19:04.3900,2018-12-12 06:35:05.8390,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26247,Subscriber,1977,2018,Male
353867,2058,2018-12-12 09:09:44.0380,2018-12-12 09:44:02.7900,3694,Jackson Square,40.711130,-74.078900,3694,Jackson Square,40.711130,-74.078900,29641,Subscriber,1957,2018,Male
353868,640,2018-12-12 11:54:45.5290,2018-12-12 12:05:25.7630,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29641,Subscriber,1994,2018,Male
353869,934,2018-12-13 06:16:06.7510,2018-12-13 06:31:41.2170,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29681,Subscriber,1977,2018,Male
353870,703,2018-12-13 12:17:13.6280,2018-12-13 12:28:57.2350,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26190,Subscriber,1994,2018,Male
353871,936,2018-12-14 06:10:18.5060,2018-12-14 06:25:54.6120,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26155,Subscriber,1977,2018,Male
353872,668,2018-12-14 12:34:01.0310,2018-12-14 12:45:09.6550,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26312,Subscriber,1994,2018,Male
353873,645,2018-12-15 13:31:59.3590,2018-12-15 13:42:45.2030,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29224,Subscriber,1994,2018,Male
353874,1396,2018-12-15 16:28:38.1250,2018-12-15 16:51:54.9460,3694,Jackson Square,40.711130,-74.078900,3279,Dixon Mills,40.721630,-74.049968,29126,Subscriber,1988,2018,Female
353875,649,2018-12-16 11:55:07.8820,2018-12-16 12:05:57.4260,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29658,Subscriber,1994,2018,Male
353876,984,2018-12-17 06:26:18.2690,2018-12-17 06:42:42.9330,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26251,Subscriber,1977,2018,Male
353877,687,2018-12-17 12:18:47.1320,2018-12-17 12:30:14.5090,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29535,Subscriber,1994,2018,Male
353878,726,2018-12-17 17:38:45.4430,2018-12-17 17:50:52.4320,3694,Jackson Square,40.711130,-74.078900,3194,McGinley Square,40.725340,-74.067622,29276,Subscriber,1973,2018,Female
353879,1041,2018-12-18 06:21:57.7450,2018-12-18 06:39:19.7440,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,29221,Subscriber,1977,2018,Male
353880,654,2018-12-18 12:12:40.2980,2018-12-18 12:23:34.4020,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29300,Subscriber,1994,2018,Male
353881,1015,2018-12-19 06:15:11.2330,2018-12-19 06:32:06.2450,3694,Jackson Square,40.711130,-74.078900,3183,Exchange Place,40.716247,-74.033459,26220,Subscriber,1977,2018,Male
353882,667,2018-12-19 11:39:50.4270,2018-12-19 11:50:58.2750,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29299,Subscriber,1994,2018,Male
353883,687,2018-12-20 13:28:39.0590,2018-12-20 13:40:06.6410,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29258,Subscriber,1994,2018,Male
353884,625,2018-12-21 12:05:04.3890,2018-12-21 12:15:29.5930,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,29664,Subscriber,1994,2018,Male
353885,826,2018-12-21 16:34:37.2330,2018-12-21 16:48:24.0150,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,26306,Subscriber,1991,2018,Male
353886,640,2018-12-22 10:27:40.6590,2018-12-22 10:38:21.4170,3694,Jackson Square,40.711130,-74.078900,3195,Sip Ave,40.730743,-74.063784,26298,Subscriber,1994,2018,Male
353887,1081,2018-12-22 11:51:46.0600,2018-12-22 12:09:47.4730,3694,Jackson Square,40.711130,-74.078900,3269,Brunswick & 6th,40.726012,-74.050389,29586,Subscriber,1993,2018,Male
353888,344,2018-12-25 21:40:09.8660,2018-12-25 21:45:54.2670,3694,Jackson Square,40.711130,-74.078900,3280,Astor Place,40.719282,-74.071262,26241,Subscriber,1983,2018,Female
353889,1233,2018-12-29 12:55:45.9690,2018-12-29 13:16:19.5960,3694,Jackson Square,40.711130,-74.078900,3186,Grove St PATH,40.719586,-74.043117,29294,Subscriber,1988,2018,Male
353890,1057,2018-12-30 15:32:09.3320,2018-12-30 15:49:46.3510,3694,Jackson Square,40.711130,-74.078900,3213,Van Vorst Park,40.718489,-74.047727,29475,Subscriber,1991,2018,Female
353891,301,2018-12-31 16:34:11.9340,2018-12-31 16:39:13.8340,3694,Jackson Square,40.711130,-74.078900,3277,Communipaw & Berry Lane,40.714358,-74.066611,26270,Subscriber,1991,2018,Male

#### Add Age Column to DataFrame

In [68]:
BikeTripDataframe['age'] = BikeTripDataframe['current year'] - BikeTripDataframe['birth year']

In [70]:
BikeTripDataframe.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,current year,gender,age
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,2018,Male,26
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2018,Female,49
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,2018,Male,72
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,2018,Male,24
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,2018,Male,27

In [71]:
BikeTripDataframe['age'].min()

16

In [78]:
BikeTripDataframe['age'].mean()

37.61212460298622

In [79]:
BikeTripDataframe['birth year'].min()

1887

In [88]:
BikeTripDataframe.count()

tripduration               353892
starttime                  353892
stoptime                   353892
start station id           353892
start station name         353892
start station latitude     353892
start station longitude    353892
end station id             353892
end station name           353892
end station latitude       353892
end station longitude      353892
bikeid                     353892
usertype                   353892
birth year                 353892
current year               353892
gender                     353892
age                        353892
dtype: int64

#### Remove Values with birth year 1887 and no gender

In [104]:
BikeTripDataframe.loc[BikeTripDataframe['birth year'] == 1887]

#### Update BikeTripDataframe to not include values where birth year is 1887

In [108]:
BikeTripDataframe = BikeTripDataframe[BikeTripDataframe['birth year']!= 1887]

In [109]:
BikeTripDataframe.count()

tripduration               353877
starttime                  353877
stoptime                   353877
start station id           353877
start station name         353877
start station latitude     353877
start station longitude    353877
end station id             353877
end station name           353877
end station latitude       353877
end station longitude      353877
bikeid                     353877
usertype                   353877
birth year                 353877
current year               353877
gender                     353877
age                        353877
dtype: int64

#### Update BikeTripDataframe to not include values where birth year is 1888

In [115]:
BikeTripDataframe = BikeTripDataframe[BikeTripDataframe['birth year']!= 1888]

In [116]:
BikeTripDataframe.count()

tripduration               353766
starttime                  353766
stoptime                   353766
start station id           353766
start station name         353766
start station latitude     353766
start station longitude    353766
end station id             353766
end station name           353766
end station latitude       353766
end station longitude      353766
bikeid                     353766
usertype                   353766
birth year                 353766
current year               353766
gender                     353766
age                        353766
dtype: int64

#### Update BikeTripDataframe to not include values where birth year is 1900

In [119]:
BikeTripDataframe.loc[BikeTripDataframe['birth year'] == 1900]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,current year,gender,age
204107,3229,2018-08-14 15:04:29.4450,2018-08-14 15:58:19.4070,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,29302,Subscriber,1900,2018,Male,118
205138,1785,2018-08-30 11:37:50.7620,2018-08-30 12:07:36.0950,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,29294,Subscriber,1900,2018,Male,118
241852,313,2018-09-02 19:11:40.3810,2018-09-02 19:16:54.2430,3195,Sip Ave,40.730743,-74.063784,3678,Fairmount Ave,40.725726,-74.071959,33569,Customer,1900,2018,Male,118
268207,346,2018-09-02 10:28:38.0940,2018-09-02 10:34:24.5070,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730743,-74.063784,29254,Customer,1900,2018,Male,118

In [120]:
BikeTripDataframe = BikeTripDataframe[BikeTripDataframe['birth year']!= 1900]

In [122]:
BikeTripDataframe['birth year'].min()

1931

### Covert merged dataset into csv file

In [124]:
BikeTripDataframe.to_csv('2018TripData.csv')